### ISSUE TITLE
Memory store is undefined error

### ISSUE THREAD

**Issue by dantebronto** [dobs/reddit-base#4]
Not sure if you still maintain this, but when making a request with a new client I get:

```
2.6.4 :013 > client.get('/r/AskReddit')
Traceback (most recent call last):
       16: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
       15: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
       14: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-0.17.3/lib/faraday/request/multipart.rb:15:in `call'
       13: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-0.17.3/lib/faraday/request/url_encoded.rb:15:in `call'
       12: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday_middleware-reddit-0.4.2/lib/faraday_middleware/reddit/request/authentication.rb:43:in `call'
       11: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-0.17.3/lib/faraday/request/retry.rb:131:in `call'
       10: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
        9: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response_middleware.rb:31:in `call'
        8: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
        7: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
        6: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
        5: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday_middleware-reddit-0.4.2/lib/faraday_middleware/reddit/use/force_json.rb:26:in `call'
        4: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-manual-cache-0.4.0/lib/faraday/manual_cache.rb:31:in `call'
        3: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-manual-cache-0.4.0/lib/faraday/manual_cache.rb:37:in `call!'
        2: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-manual-cache-0.4.0/lib/faraday/manual_cache.rb:67:in `cached_response'
        1: from /Users/X/.rvm/gems/ruby-2.6.4/gems/faraday-manual-cache-0.4.0/lib/faraday/manual_cache.rb:92:in `store'
```

It works if I run with `nocache: true` Am I supposed to setup a cache?

**Comment by dobs** [comment]
Hey @dantebronto -- you're correct, I haven't been maintaining this.

The `faraday-manual-cache` docs have some details on setting up caching: https://github.com/dobs/faraday-manual-cache

Leaving this issue open in case someone wants to tackle or I get a change to address myself. Relying on Rails store is probably overkill.

**Comment by GauthierPLM** [comment]
I also had the issue, the `nocache: true` fixes it.
